FROM nginx:1.19.2-alpine
RUN apk add --update nodejs nodejs-npm

COPY ./docker/nginx/default.conf /etc/nginx/conf.d/default.conf
COPY ./frontend /tmp/app
RUN cd /tmp/app && npm install && npm run build && cp -r build /var/www && rm -rf /tmp/app
EXPOSE 80

ENTRYPOINT ["nginx","-g","daemon off;"]